/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 14:46:41 GMT 2020
 */

package org.zalando.jackson.datatype.money;

import org.junit.Test;
import static org.junit.Assert.*;
import java.math.BigDecimal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.zalando.jackson.datatype.money.DecimalAmountWriter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BigDecimalAmountWriter_ESTest extends BigDecimalAmountWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DecimalAmountWriter decimalAmountWriter0 = new DecimalAmountWriter();
      Class<BigDecimal> class0 = decimalAmountWriter0.getType();
      assertEquals("class java.math.BigDecimal", class0.toString());
  }
}
