/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 14:46:03 GMT 2020
 */

package org.zalando.jackson.datatype.money;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonFormatVisitorWrapper;
import com.fasterxml.jackson.databind.jsonFormatVisitors.JsonStringFormatVisitor;
import javax.money.CurrencyUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.zalando.jackson.datatype.money.CurrencyUnitSerializer;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CurrencyUnitSerializer_ESTest extends CurrencyUnitSerializer_ESTest_scaffolding {

 
  /**
   * COMPREENSÍVEL: Sim
   * DE FÁCIL CRIAÇÃO: Sim
   * IMPORTANTE PARA O CONTEXTO: Sim
   * ----------------------------------------------------------
   * DESCRIÇÃO: O teste em questão verifica se o método 
   * acceptJsonFormatVisitor realmente gera uma exceção ao
   * receber como parâmetro um JsonFormatVisitorWrapper, sendo que
   * dentro do método esse parâmetro não é tratado como nulo, ou
   * seja: Ao entrar no método, um método do parâmetro é chamado,
   * gerando um NullPointerException quando o parâmetro é nulo.
   * ----------------------------------------------------------
  */
  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CurrencyUnitSerializer currencyUnitSerializer0 = new CurrencyUnitSerializer();
      JavaType javaType0 = mock(JavaType.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        currencyUnitSerializer0.acceptJsonFormatVisitor((JsonFormatVisitorWrapper) null, javaType0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.zalando.jackson.datatype.money.CurrencyUnitSerializer", e);
      }
  }

  /**
   * COMPREENSÍVEL: Não
   * DE FÁCIL CRIAÇÃO: Não
   * IMPORTANTE PARA O CONTEXTO: Não foi possível determinar
   * ----------------------------------------------------------
   * DESCRIÇÃO: Não foi possível compreender o funcionamento
   * do teste em questão. Por esse motivo não consegui determinar
   * se teste é importante para o contexto.
   * ----------------------------------------------------------
  */
  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CurrencyUnitSerializer currencyUnitSerializer0 = new CurrencyUnitSerializer();
      CurrencyUnit currencyUnit0 = mock(CurrencyUnit.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(currencyUnit0).getCurrencyCode();
      JsonGenerator jsonGenerator0 = mock(JsonGenerator.class, new ViolatedAssumptionAnswer());
      currencyUnitSerializer0.serialize(currencyUnit0, jsonGenerator0, (SerializerProvider) null);
      assertFalse(currencyUnitSerializer0.usesObjectId());
  }

  /**
   * COMPREENSÍVEL: Não
   * DE FÁCIL CRIAÇÃO: Não
   * IMPORTANTE PARA O CONTEXTO: Não foi possível determinar
   * ----------------------------------------------------------
   * DESCRIÇÃO: Não foi possível compreender o funcionamento
   * do teste em questão. Por esse motivo não consegui determinar
   * se teste é importante para o contexto.
   * ----------------------------------------------------------
  */
  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CurrencyUnitSerializer currencyUnitSerializer0 = new CurrencyUnitSerializer();
      JsonFormatVisitorWrapper jsonFormatVisitorWrapper0 = mock(JsonFormatVisitorWrapper.class, new ViolatedAssumptionAnswer());
      doReturn((JsonStringFormatVisitor) null).when(jsonFormatVisitorWrapper0).expectStringFormat(any(com.fasterxml.jackson.databind.JavaType.class));
      JavaType javaType0 = mock(JavaType.class, new ViolatedAssumptionAnswer());
      currencyUnitSerializer0.acceptJsonFormatVisitor(jsonFormatVisitorWrapper0, javaType0);
      assertFalse(currencyUnitSerializer0.isUnwrappingSerializer());
  }
}
