/*
 * This file was automatically generated by EvoSuite
 * Wed Feb 26 14:47:49 GMT 2020
 */

package org.zalando.jackson.datatype.money;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import javax.money.MonetaryAmount;
import javax.money.NumberValue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.zalando.jackson.datatype.money.QuotedDecimalAmountWriter;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class QuotedDecimalAmountWriter_ESTest extends QuotedDecimalAmountWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QuotedDecimalAmountWriter quotedDecimalAmountWriter0 = new QuotedDecimalAmountWriter();
      Class<String> class0 = quotedDecimalAmountWriter0.getType();
      assertFalse(class0.isInterface());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QuotedDecimalAmountWriter quotedDecimalAmountWriter0 = new QuotedDecimalAmountWriter();
      MonetaryAmount monetaryAmount0 = mock(MonetaryAmount.class, new ViolatedAssumptionAnswer());
      doReturn((NumberValue) null).when(monetaryAmount0).getNumber();
      // Undeclared exception!
      try { 
        quotedDecimalAmountWriter0.write(monetaryAmount0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.zalando.jackson.datatype.money.DecimalAmountWriter", e);
      }
  }
}
